[package]
name = "day_01b"
version = "0.1.0"
authors = ["Brad Gibson <b2b@humanenginuity.com>"]
edition = "2018"

[[bin]]
doc = false
name = "day_01b"
path = "src/main.rs"
test = false

[dependencies]
derive_more = "*"
num-traits = "*"
